# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: "/usr/bin/env /home/gitpod/.sdkman/candidates/java/11.0.17.fx-zulu/bin/java @/tmp/cp_45036b9d79fota19uurnaxh0u.argfile LambdaTestSample.LambdaTestScenarios"

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
