tasks:
- command: yarn start
  label: Run development server
  group: Run
  depends_on: [workspace-start]
  when:
    event: workspace-start
- command: chromium-browser --no-sandbox https://localhost:3000
  label: Open browser
  group: Run
  depends_on: [workspace-start]
  when:
    event: workspace-start

